extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MinMaxObserver
        a_observer: EMAMinMaxObserver
        w_fakequantize: AdaRoundFakeQuantize
        a_fakequantize: QDropFakeQuantize
        w_qscheme:
            bit: 2
            symmetry: False
            per_channel: True
            pot_scale: False
        a_qscheme:
            bit: 4
            symmetry: False
            per_channel: False
            pot_scale: False
quantize:
    quantize_type: advanced_ptq # support naive_ptq or advanced_ptq
    cali_batchsize: 2
    reconstruction:
        pattern: block
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.01
        max_count: 20
        b_range: [20,2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        prob: 1.0

model:                    # architecture details
    type: resnet18       # model name
    kwargs:
        num_classes: 1000
    path: /home/local/SENSETIME/fanyunqian/.cache/torch/hub/checkpoints/resnet18.pth.tar
data:
    path: /data/imagenet
    batch_size: 4
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005
dist:
    backend: dist
    port: 13333
    launch: pytorch